### ISSUE TITLE
Add support for passing an arbitrary Context through the render/render_mut APIs 

### ISSUE THREAD

**Issue by Uriopass** [aclysma/imgui-inspect#3]
I'm posting this as an issue, but It's really a usability question and maybe there's a way to do this that I haven't seen.

I'm using this crate to inspect an `Entity` using `specs`, however I found that there was no way for the render functions to use the `World` reference, which makes indirection impossible.  

For example I have a car entity which has a component `Objective`, the objective corresponds to the id of a node in the road graph. 
I would like in the inspector to show the position of this node instead of just an id (which is pretty meaningless).

Is there a way to do this already ? Or does this require significant work ? Maybe some way of passing the world in the InspectArgs ?  
I also thought about forking the crate to add a "Option<&mut World>" to the render trait and derive mechanism or something like that.

**Comment by aclysma** [comment]
Sorry, I'm in the middle of a move so I've been pretty busy!

I suppose we could add an additional generic parameter "context" that would allow the user to pass whatever they like (or `()` if they don't have anything they want to pass.)

BTW you might want to take a look at the way I use this library in minimum. I implemented a registry for the different types that can be inspected, this avoided needing to have access to World in the implementing code: https://github.com/aclysma/minimum/tree/master/minimum-framework/src/inspect

However, a context parameter still seems like a very reasonable thing to support and the "registry" approach still doesn't do much for letting the code read resources. But maybe it could solve your immediate needs in the meantime?

**Comment by Uriopass** [comment]
I forked the project and added this World context everywhere, if you want to look. :)  
The only problem I see is that to access the context in the lower structs, it has to be passed to all of the hierarchy.   
So in the end, everyone has to have it.   
But not everyone needs it.  

I would be very pleased if you would take a go at it! What I did is not a very nice API since I pass the &mut World everywhere, whereas most of the implementing structs don't need it.  
I also tried putting it in the InspectArgsStructs but couldn't get it to work (but that's probably since I didn't try hard enough). 


I did see your project but it does not solve my indirection problem as I can't access ressources from the structs.

**Comment by aclysma** [comment]
I just pushed a demo project so that iterating on this can be a bit easier. Hopefully I will get some time to work on this in the next day or two!

**Comment by Uriopass** [comment]
Very cool ! I hope you have some time too, moving is not easy. :)

**Comment by aclysma** [comment]
I added a branch generic_param which has what I had in mind, but it's not quite compiling yet. Do you think something like this would work for you?

**Comment by Uriopass** [comment]
That's indeed what I had in mind ! I'm just wondering if there is a way to put the context in the InspectArgs to not clutter the render trait.
And it also has to work with the render_trait parameter etc

**Comment by aclysma** [comment]
I played with this a bit but couldn't find a way to get it to work in practice. I did something like this before (generic context arg) in another library so I thought this would be possible and straightforward to do, but that change was adding the args to a function and it seems a bit trickier to make it work with a trait. (The reason this library uses traits in this way is to allow a single type to implement its rendering for multiple widget types.. sometimes an i32 should be on a slider but other times it might not make sense to do it that way.)

I would lean towards keeping it in the function rather than the args - one reason being that the options arg is intended to hold options that might change depending on the widget type and I think this context parameter should go on everything. The other reason is that we'd have to remember to add it to every InspectArgs which is again, once per widget type.

In the meantime, if you're willing to use thread local vars and maybe some unsafe code, I'm sure you can get it to work, and the ugliness involved can probably be wrapped so that it's at least contained in one spot. I'm going to be using this library a bit more in the next couple weeks hopefully and I'll definitely keep my eye out for a good way to do this - I might end up needing it too :)

**Comment by Uriopass** [comment]
Indeed, I agree with you now, I think it should go in the function args.
