### ISSUE TITLE
use mint types 

### ISSUE THREAD

**Issue by benmkw** [aclysma/imgui-inspect#8]
I think once [this issue](https://github.com/kvark/mint/issues/59) is solved it would open up a whole lot more possibilities out of the box 

ping @LPGhatguy

**Comment by LPGhatguy** [comment]
I stalled on trying to create a separate crate for these conversions. I'm not sure what exact issues I hit, but it might be worth revisiting.

If this project has a good use case for the trait, you should post a comment in that thread with details. I think that one thing kvark is looking for is more users, since the change would be invasive and require an ecosystem-wide upgrade.

**Comment by aclysma** [comment]
The approach I've taken is to newtype the math library I use (glam) so that I can impl the traits. Here's an example: https://github.com/aclysma/minimum/blob/master/minimum-math/src/math.rs

A big advantage of this approach is it keeps this crate unopinionated and minimal. I'd rather see opinionated choices (what math library to use, how exactly to render math types) in a separate crate layered on top of this one.

**Comment by LPGhatguy** [comment]
The file you mentioned there is very similar to what mint does. mint is not an opinionated math library choice, it is the piece that helps all of them mesh together.

Implementing your traits for mint types would enable interop with any math library in the Rust ecosystem, including glam. They may be a nearly drop-in replacement, in fact!

**Comment by aclysma** [comment]
Mint, like every other math library, is opinionated on memory layout. In my own code I use SIMD vectors (I'm on an older version of glam before they changed to non-SIMD by default). So an array of Vec3 for me is a different alignment from an array of mint Vec3. In my case, using mint would involve copying all the data into a different alignment and back again. Implementing inspect traits for glam newtype wrappers avoids the overhead and additional dependency.

I would rather see implementations for specific math libraries (even if it's a math library that just does interchange) in a downstream crate. 

One alternative does come to mind.. maybe we could implement inspect types for native rust types like [f32; 3] or __m128 (maybe provide new-typed Vec2(__m128), Vec3(__m128), etc. since __m128 could be different number of components). The advantage here is that there would be no external dependencies. Most math libraries expose an internally held value that may already be those types, or easily convert/transmute to them.

This still ignores that deciding how to render a type is itself opinionated. I think it could be argued that this crate should not contain implementations for ANY types. But providing implementations just for standard rust types seems like a good middle ground, especially since most any rust library can easily convert to/from standard rust types (like [f32; 3].)

**Comment by aclysma** [comment]
After giving it some thought for a few days, I think support for specific math libraries is out of scope for imgui-inspect itself ("... this crate aims to be a serde for inspecting with imgui. It defines a common interface for getting values into imgui and back out.") and can be implemented in a downstream crate. Even if I felt differently about it, I'd want to see the proposed implementation developed independently in a downstream crate and see some dogfooding before considering merging it into the imgui-inspect crate directly (possibly behind a feature flag.) However, I'm happy to consider PRs for a few simple built-in rust types (like [f32; 3]).

**Comment by benmkw** [comment]
I think it should be as easy as adding a derive on a struct and maybe adding some annotations (like „this represents a color“) because without that derive option it’s basically the same amount of typing as just writing it from scratch with maybe a few helper functions. And for that to work for all structs, support for math crates is necessary or else one ends up with n times m implementations (n display formats for m math crates) instead of just n for mint.
But as discussed in the mint thread that derive support will only be possible when specialisation is available (at least the way I thought about it).
